/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeyId = IDL.Nat;
export const Time = IDL.Int;
export const LoginKey = IDL.Record({
  'id' : KeyId,
  'key' : IDL.Text,
  'created' : Time,
  'expires' : IDL.Opt(Time),
  'blocked' : IDL.Bool,
  'used' : IDL.Nat,
});

export const idlService = IDL.Service({
  'blockKey' : IDL.Func([KeyId], [], []),
  'createKey' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllKeys' : IDL.Func([], [IDL.Vec(LoginKey)], ['query']),
  'getKeyById' : IDL.Func([KeyId], [LoginKey], ['query']),
  'isValidKey' : IDL.Func([KeyId], [IDL.Bool], []),
  'unblockKey' : IDL.Func([KeyId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeyId = IDL.Nat;
  const Time = IDL.Int;
  const LoginKey = IDL.Record({
    'id' : KeyId,
    'key' : IDL.Text,
    'created' : Time,
    'expires' : IDL.Opt(Time),
    'blocked' : IDL.Bool,
    'used' : IDL.Nat,
  });
  
  return IDL.Service({
    'blockKey' : IDL.Func([KeyId], [], []),
    'createKey' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllKeys' : IDL.Func([], [IDL.Vec(LoginKey)], ['query']),
    'getKeyById' : IDL.Func([KeyId], [LoginKey], ['query']),
    'isValidKey' : IDL.Func([KeyId], [IDL.Bool], []),
    'unblockKey' : IDL.Func([KeyId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };