/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type KeyId = bigint;
export interface LoginKey {
  'id' : KeyId,
  'key' : string,
  'created' : Time,
  'expires' : [] | [Time],
  'blocked' : boolean,
  'used' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'blockKey' : ActorMethod<[KeyId], undefined>,
  'createKey' : ActorMethod<[string, bigint], undefined>,
  'getAllKeys' : ActorMethod<[], Array<LoginKey>>,
  'getKeyById' : ActorMethod<[KeyId], LoginKey>,
  'isValidKey' : ActorMethod<[KeyId], boolean>,
  'unblockKey' : ActorMethod<[KeyId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];